// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acxftnygtlqnmxighelr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjeGZ0bnlndGxxbm14aWdoZWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDU1NjMsImV4cCI6MjA3MzE4MTU2M30.NX9PmYAHV7NccydrXBc3hFjIy42UDsgB9-ui3SXuRqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});